config/routes.rb
Rails.application.routes.draw do
  get 'payment/page'
  root 'home#page'
  resources :reviews
  resources :listings
  resources :profiles
  devise_for :users
  post 'payment/page', to: 'payment#create', as: 'payment'
  get 'payment/cancel', to: 'payment#cancel', as: 'payment_cancel'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  # belongs_to :profile

  belongs_to :buyer, class_name: "Profile", optional: true
  belongs_to :seller, class_name: "Profile", optional: true

  has_many_attached :pictures

  validates :price, presence: true

  before_validation :validate_title

  before_save :remove_whitespace
  # data sanitization, custom model methods
  def validate_title
    if self.title.length < 3
      # throw error, a custom error would be nice
      errors.add :base, :invalid, message: "The title is invalid, need at least 3 valid characters."
    end
  end

  def remove_whitespace
    self.title = self.title.strip
    self.description = self.description.strip
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_listing, only: %i[ show edit update destroy ]
  
  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
    if params[:checkout] == "success"
      # update buyer
      @listing.buyer_id = current_user.profile.id
      @listing.save
    end
  end

  # GET /listings/new
  def new
    # if the user is not logged in, redirect to the login page
    # else redirect to the listing page
    if user_signed_in?
      # if user has created a profile, show car form, else redirect to create a profile page
      if current_user.profile
        @listing = Listing.new
      else
        redirect_to new_profile_path
      end
    else
      redirect_to new_user_session_path
    end
  end
  
  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)
    
    # associate the car listed to a seller
    @listing.seller_id = current_user.profile.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:title, :description, :price, :fuel_type, :make, :car_type, :buyer_id, :seller_id, :profile_id, pictures: [])
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :fuel_type %>
    <%= f.input :make %>
    <%= f.input :car_type %>
    <%= f.file_field :pictures, multiple: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Fuel type</th>
      <th>Make</th>
      <th>Car type</th>
      <th>Picture</th>
      <th>Buyer</th>
      <th>Seller</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.title %></td>
        <td><%= listing.description %></td>
        <td><%= listing.price %></td>
        <td><%= listing.fuel_type %></td>
        <td><%= listing.make %></td>
        <td><%= listing.car_type %></td>
        
        <td><%= listing.buyer_id %></td>
        <td><%= listing.seller_id %></td>
        <td><%= listing.profile_id %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Fuel type:</strong>
  <%= @listing.fuel_type %>
</p>

<p>
  <strong>Make:</strong>
  <%= @listing.make %>
</p>

<p>
  <strong>Car type:</strong>
  <%= @listing.car_type %>
</p>

<p>
  <strong>Picture:</strong>
  <% @listing.pictures.each do |pic|%>
    <%= image_tag pic %>
  <% end %>
</p>

<p>
  <strong>Buyer:</strong>
  <%= @listing.buyer_id %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @listing.seller.user_name %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @listing.profile_id %>
</p>

<!-- If the car listed is by the seller who is logged in, show edit button -->
<% # if user is logged in and has a profile and id matches seller of listing %>
<% if current_user && current_user.profile && (current_user.profile.id == @listing.seller.id) %>
  <%= link_to 'Edit', edit_listing_path(@listing) %>
<% else %>
  <% # if the car has a buyer then provide sold button else show buy button %>
  <% if @listing.buyer %>
    <button class="btn btn-danger">SOLD</button>
  <% else %>
    <% if current_user && current_user.profile %>
      <%= link_to "Buy", payment_path(listing_id: @listing.id), method: :post, class: "btn btn-primary" %>
    <% end %>
  <% end %>
<% end %>

<%= link_to 'Back', listings_path %>