config/routes.rb
Rails.application.routes.draw do
  get 'payment/page'
  root 'home#page'
  resources :reviews
  resources :listings
  resources :profiles
  devise_for :users
  post 'payment/page', to: 'payment#create', as: 'payment'
  get 'payment/cancel', to: 'payment#cancel', as: 'payment_cancel'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
    @listings = Listing.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/page.html.erb
<div class="container-fluid">
  <div id="navbarSupportedContent">
    <form class="d-flex search-bar">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</div>

<div class="row">
  <% @listings.each do |car| %>  
    <div class="col-md-4">
      <div class="card" style="width: 18rem;">
        <% if car.pictures && car.pictures.first %>
          <%= image_tag car.pictures.first, class: "card-img-top" %>
        <% else %>
          <%= image_tag "car.jpg", class: "card-img-top" %>
        <% end %>
        <h5 class="card-title">
            <%= car.title %>
        </h5>
        <p class="card-text">
          $<%= car.price %>
        </p>
        <p class="card-text">
          <%= link_to "Explore", listing_path(car.id), class: "btn btn-primary" %>
        </p>
      </div>
    </div>
  <% end %>
</div>